# Generated by Django 5.1.6 on 2025-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='source',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(blank=True, help_text='Full address', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_request',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
