# Generated by Django 5.1.6 on 2025-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_remove_visitor_source_alter_visitor_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['name'], 'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(blank=True, help_text='Full address (e.g., 3621 Tallevast Rd, Sarasota FL 34243)', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(help_text='Full name of the visitor', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number in E.164 format (e.g., +19415382650)', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='sms_opt_in',
            field=models.BooleanField(default=False, help_text='Indicates if the visitor opts in to receive SMS notifications'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Date of the requested visit, if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_request',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Indicates if the visitor requests a home visit', max_length=3),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current status of the visit request', max_length=20),
        ),
    ]
